# Generated by Django 4.2.4 on 2023-10-19 17:34

from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(validators=[main_app.validators.validate_age]),
        ),
    ]
