"""Add User Table

Revision ID: 88357a3567f1
Revises: 
Create Date: 2023-11-14 18:47:24.236348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88357a3567f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('users')
    pass
    # ### end Alembic commands ###
